[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "symbol-mangling-version=v0",
    "-C", "link-arg=-lSDL2",
    "-C", "link-arg=-lhtml5",
    "-Z", "emscripten-wasm-eh",
]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
